r"""Part 9 addendum -- "geometry shapes the global pressure" demonstration.

Spins up a developed idealized cavity, adds a single localized bed bump, and shows
that the resulting localized continuity source produces a *global* pressure
response (elliptic, inverse-Laplacian, ~ln r in 2D) but only a *local* temperature
response (parabolic, heat kernel, Gaussian).  Same source, two operators -> the two
clocks made literal, driven purely by the solid geometry.

  python run_elliptic_demo.py --out-dir figures --report REPORT_ELLIPTIC_PRESSURE.md
"""
from __future__ import annotations

import argparse
import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import sys
# repo reorg: make sibling domain folders importable
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _d in ("general_two_clocks", "atmosphere", "glaciers", "ocean"):
    _p = os.path.join(_REPO_ROOT, _d)
    if _p not in sys.path:
        sys.path.insert(0, _p)
del _d, _p

from subglacial.flow import SubglacialFlow, SubglacialConfig
from subglacial.elliptic_demo import (
    geometry_bump, obstacle_source, elliptic_response, parabolic_response,
    diffusion_time_for_length, radial_from, radial_profile, far_fraction,
)

FIGNUM = 39


def fig_elliptic(f, bump, center, q, dp, dth, r, kappa, tstar, out_dir, num=FIGNUM):
    fluid = f.fluid
    X, Y = f.X, f.Y
    ybed = f.ybed[:, 0]
    x = X[:, 0]
    rc, pp = radial_profile(dp, r, fluid)
    _, pt = radial_profile(dth, r, fluid)
    ff_p = far_fraction(dp, r, fluid)
    ff_t = far_fraction(dth, r, fluid)

    def mask_solid(a):
        return np.ma.masked_where(~fluid, a)

    fig, ax = plt.subplots(2, 2, figsize=(12.5, 9))
    fig.suptitle("Part 9 — geometry shapes the GLOBAL pressure, only the LOCAL "
                 "temperature\n(same localized bed bump; elliptic vs parabolic "
                 "response)", fontsize=13)

    # (a) the added bump + localized source q
    a = ax[0, 0]
    qlim = np.nanpercentile(np.abs(mask_solid(q).compressed()), 99.5)
    im = a.pcolormesh(x, Y[0], mask_solid(q).T, cmap="RdBu_r",
                      vmin=-qlim, vmax=qlim, shading="auto")
    a.plot(x, ybed, "k", lw=1.2)
    a.contour(X.T, Y.T, bump.T, levels=[0.3], colors="k", linewidths=1.0)
    a.set_title("(a) one localized bed bump → localized continuity source q")
    a.set_xlabel("x"); a.set_ylabel("y"); fig.colorbar(im, ax=a, shrink=0.8)

    # (b) elliptic pressure response (global)
    b = ax[0, 1]
    vlim = np.nanpercentile(np.abs(mask_solid(dp).compressed()), 99)
    im = b.pcolormesh(x, Y[0], mask_solid(dp).T, cmap="RdBu_r",
                      vmin=-vlim, vmax=vlim, shading="auto")
    b.plot(x, ybed, "k", lw=1.2)
    b.plot(center[0], center[1], "k*", ms=11)
    b.set_title(f"(b) pressure Δp = ∇⁻²q  —  GLOBAL (elliptic)\n"
                f"{ff_p*100:.0f}% of |Δp| lies beyond one bump-width of the source")
    b.set_xlabel("x"); b.set_ylabel("y"); fig.colorbar(im, ax=b, shrink=0.8)

    # (c) parabolic temperature response (local)
    c = ax[1, 0]
    vlim = np.nanpercentile(np.abs(mask_solid(dth).compressed()), 99)
    im = c.pcolormesh(x, Y[0], mask_solid(dth).T, cmap="RdBu_r",
                      vmin=-vlim, vmax=vlim, shading="auto")
    c.plot(x, ybed, "k", lw=1.2)
    c.plot(center[0], center[1], "k*", ms=11)
    c.set_title(f"(c) temperature Δθ = e^(t*∇²)q  —  LOCAL (parabolic)\n"
                f"only {ff_t*100:.0f}% beyond one bump-width "
                f"(diffused √(4κt*)≈{np.sqrt(4*kappa*tstar):.2f})")
    c.set_xlabel("x"); c.set_ylabel("y"); fig.colorbar(im, ax=c, shrink=0.8)

    # (d) radial decay
    d = ax[1, 1]
    d.semilogy(rc, np.clip(pp, 1e-3, None), "o-", color="#b5402a",
               label=f"|Δp| pressure (elliptic), far-frac {ff_p:.2f}")
    d.semilogy(rc, np.clip(pt, 1e-3, None), "s-", color="#2a6f9e",
               label=f"|Δθ| temperature (parabolic), far-frac {ff_t:.2f}")
    d.axvline(0.6, color="gray", ls=":", lw=1)
    d.set_ylim(1e-3, 1.5)
    d.set_title("(d) radial decay from the bump (normalised)")
    d.set_xlabel("distance r from source"); d.set_ylabel("mean |response|")
    d.legend(fontsize=9); d.grid(alpha=0.3)

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    path = os.path.join(out_dir, f"{num}_elliptic_pressure.png")
    fig.savefig(path, dpi=110); plt.close(fig)
    return path, ff_p, ff_t


REPORT = """<!-- GENERATED by run_elliptic_demo.py. Re-run to refresh. -->

# Part 9 addendum — geometry shapes the *global* pressure, only the *local* temperature

A reviewer's intuition (and the user's): *the geometry of the solids shapes the
solid/fluid boundary, which shapes the pressure boundaries.* This note turns that
into a computed picture and shows exactly why it implies K-theory cannot work.

**Experiment.** Take a developed idealized cavity (frozen field), add a **single
localized bump** to the bed, and read off the localized continuity source it
creates in the oncoming stream, `q = -∇·(bump·u)`. Apply that *same* source to the
two operators the thesis separates — both are functions of the Laplacian:

| clock | operator | Green's function (2D) | response to a localized source |
|---|---|---|---|
| pressure (elliptic) | `lap^-1` (steady Poisson) | `~ln r` | **global** — felt across the whole cavity, at once |
| temperature (parabolic) | `exp(t*lap)` (heat kernel) | Gaussian, width `sqrt(4*kappa*t)` | **local** — a confined blob |

![elliptic vs parabolic](%%FIG%%)

**Result (computed).** From the identical bump-induced source:

- **Pressure response `Dp = lap^-1 q`:** %%FFP%%% of its magnitude sits *beyond one
  bump-width* of the source — it spans the cavity, reaching the ice base and the
  neighbouring bumps. This is the elliptic "fast clock": the boundary geometry is
  felt everywhere instantaneously.
- **Temperature response `Dth = exp(t*lap) q`:** only %%FFT%%% beyond one
  bump-width, even after a diffusion time `t*` long enough to spread a full
  bump-width (`sqrt(4*kappa*t*) ~ %%DIFFLEN%%`, ~ %%TADV%% flow-through times). It
  stays a local blob.

**Why this kills K-theory.** A single eddy diffusivity models the subgrid force as
`nu_t * lap(u_bar)` — a *parabolic, neighbour-to-neighbour* operator. It is, by construction,
in the right column of the table above: it can only ever produce **local**
responses. But the pressure that enforces incompressibility lives in the **left**
column — it is the *global* `lap^-1` of the geometry-induced source. No local
diffusivity, however tuned, can reproduce a global inverse-Laplacian. That is the
structural blindness Parts 1–9 keep measuring, here reduced to a single source and
two operators. The bed geometry is what injects the source; the elliptic operator
is what makes its effect global.

*Scope:* a frozen-field, single-perturbation linear-response demonstration in the
periodic penalized box (same caveats as the rest of Part 9). It illustrates the
operator-level mechanism; it is not a time-integrated glacier simulation.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default="figures")
    ap.add_argument("--report", default="REPORT_ELLIPTIC_PRESSURE.md")
    ap.add_argument("--n", type=int, default=128)
    ap.add_argument("--steps", type=int, default=3000)
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    cfg = SubglacialConfig(n=args.n, sgs="none", f_amp=1.5, k_f=10.0, f_band=2.0, seed=1)
    f = SubglacialFlow(cfg)
    print(f"spinning up developed cavity (n={args.n}, steps={args.steps}) ...")
    f.run(args.steps, ramp=args.steps // 2)
    print(f"  KE={f.kinetic_energy():.4e}")

    bump, center = geometry_bump(f, x0=np.pi)
    q = obstacle_source(f, bump)
    sp = f.sp
    tstar = diffusion_time_for_length(0.18, cfg.kappa)   # spread ~ one bump-width
    dp = elliptic_response(sp, q)
    dth = parabolic_response(sp, q, cfg.kappa, tstar)
    r = radial_from(f, center)

    path, ff_p, ff_t = fig_elliptic(f, bump, center, q, dp, dth, r,
                                    cfg.kappa, tstar, args.out_dir)
    print(f"  -> {path}")
    print(f"  far-fraction: elliptic Δp={ff_p:.3f}  parabolic Δθ={ff_t:.3f}")

    difflen = float(np.sqrt(4 * cfg.kappa * tstar))
    tadv = tstar / (2 * np.pi / cfg.U0)
    body = (REPORT.replace("%%FIG%%", os.path.basename(path))
                  .replace("%%FFP%%", f"{ff_p*100:.0f}")
                  .replace("%%FFT%%", f"{ff_t*100:.0f}")
                  .replace("%%DIFFLEN%%", f"{difflen:.2f}")
                  .replace("%%TADV%%", f"{tadv:.1f}"))
    with open(args.report, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"Report: {args.report}")


if __name__ == "__main__":
    main()
